### PR TITLE
sps: Version bump

### PR DESCRIPTION
**Pull request by szszeker**
Scope: SafeguardSession\modules\version\SupportedVersions.pqm

References: azure #422225

### CODE REVIEW

**Comment by szszeker** [comment]
Based on the discussion with Szabolcs Szondi, the current version is _v1.1.1pre1+sps7.4_

**Review by asulyi — APPROVED** [review]
It works for me at the moment.

But, I'm not very keen of the fact that version number is fixed in tests.  It makes manual maintenance  harder or implementing an automatic release solution.

**Review by davedusa — CHANGES_REQUESTED** [review]
Just a small commit message typo:
> bumpp -> bump

**Comment by szszeker** [comment]
> It works for me at the moment.
> 
> But, I'm not very keen of the fact that version number is fixed in tests. It makes manual maintenance harder or implementing an automatic release solution.

Me neither. We can use Extension.LoadString("ReleaseVersion") in the tests. That leaves 2 modifications for each release: version in SafeguardSession.pq and ReleaseVersion in resources.resx. We could implement it for the actual release.

I tried to use the version from the resource file at the top of the main .pq file, but it is not possible.

**Comment by szszeker** [comment]
> Just a small commit message typo:
> 
> > bumpp -> bump

Commit title and scope are fixed

**Review by davedusa — APPROVED** [review]

**Review by marcellmeszaros — APPROVED** [review]
Looks good to me.

**Pull request merged**
