### PR TITLE
SPP - Initial PR to add support for SPP Data Connector 

### PR DESCRIPTION
**Pull request by aamburn**
Logic and files to add SPP Data Connector. Most are contained in the SafeguardPasswords directory. 

References: azure #256846

### CODE REVIEW

**Review by szszeker — COMMENTED** [review]
I haven't checked all the commits yet but I saw that no tests have been written yet. Just a heads up, but some tests will be a must have before integration.

**Comment by aamburn** [comment]
> I haven't checked all the commits yet but I saw that no tests have been written yet. Just a heads up, but some tests will be a must have before integration.

That isn't a problem; I have some questions about your unit test framework; I'll contact you out of band to resolve.

**Comment by szszeker** [comment]
> > I haven't checked all the commits yet but I saw that no tests have been written yet. Just a heads up, but some tests will be a must have before integration.
> 
> That isn't a problem; I have some questions about your unit test framework; I'll contact you out of band to resolve.

Feel free to hit me up on teams. ;)

**Comment by aamburn** [comment]
I am preparing another PR ready; closing this for now.

**Pull request closed without merging**
